utils::globalVariables(
  c(
    '.',
    'segment_id',
    'car',
    'heavy',
    'pedestrian',
    'bike',
    'bike_lft',
    'bike_rgt',
    'car_lft',
    'car_rgt',
    'heavy_lft',
    'heavy_rgt',
    'pedestrian_lft',
    'pedestrian_rgt',
    'uptime',
    'description',
    'start_date',
    'end_date',
    'car_speed_hist_0to70plus',
    'vit_moins10',
    'vit_moins20',
    'vit_moins30',
    'vit_moins40',
    'vehic'
  )
)
